[build]
  base = "client"
  command = "cd client && npm install && npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20.12.2"
  PNPM_VERSION = "9.0.0"
  NPM_FLAGS = "--no-audit --no-fund"