[build]
  command = "cd client && chmod +x build.sh && ./build.sh"
  publish = "client/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20.12.2"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
  NPM_CONFIG_PACKAGE_LOCK = "false"