[build]
  command = "cd client && npm install --legacy-peer-deps --no-package-lock --no-audit --no-fund && npm run build"
  publish = "client/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "22"
  NPM_VERSION = "10.8.2"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
  NPM_CONFIG_PACKAGE_LOCK = "false"
  NPM_CONFIG_AUDIT = "false"
  NPM_CONFIG_FUND = "false"
  NODE_OPTIONS = "--max-old-space-size=4096"