[build]
  base = "client"
  command = "npm install -g pnpm@9.0.0 && pnpm install --no-frozen-lockfile --shamefully-hoist --strict-peer-deps=false && pnpm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20.12.2"
  NPM_CONFIG_PACKAGE_MANAGER = "pnpm"