[build]
  base = "client"
  command = "yarn install --frozen-lockfile=false && yarn build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20.12.2"
  YARN_VERSION = "1.22.19"