[build]
  base = "client"
  command = "npx pnpm install --no-frozen-lockfile && npx pnpm build"
  publish = "client/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18.19.0"