[build]
  base = ""
  command = "cd client && npx pnpm install --no-frozen-lockfile && npx pnpm build"
  publish = "client/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20.12.2"
  NPM_FLAGS = "--no-audit --no-fund"